# Generated by Django 5.1.1 on 2024-11-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='strength',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
